/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedBibliothequeRouteImport } from './routes/_authenticated/bibliotheque'
import { Route as AuthenticatedComparaisonRouteImport } from './routes/_authenticated/comparaison'
import { Route as AuthenticatedMontageRouteImport } from './routes/_authenticated/montage'
import { Route as AuthenticatedStatistiquesRouteImport } from './routes/_authenticated/statistiques'
import { Route as AuthenticatedStoryboardRouteImport } from './routes/_authenticated/storyboard'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as FTokenRouteImport } from './routes/f.$token'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAnalysesRouteImport } from './routes/_authenticated/admin/analyses'
import { Route as AuthenticatedAdminClesApiRouteImport } from './routes/_authenticated/admin/cles-api'
import { Route as AuthenticatedAdminCoutsRouteImport } from './routes/_authenticated/admin/couts'
import { Route as AuthenticatedAdminJournalRouteImport } from './routes/_authenticated/admin/journal'
import { Route as AuthenticatedAdminParametresRouteImport } from './routes/_authenticated/admin/parametres'
import { Route as AuthenticatedAdminScenesRouteImport } from './routes/_authenticated/admin/scenes'
import { Route as AuthenticatedAdminStoryboardsRouteImport } from './routes/_authenticated/admin/storyboards'
import { Route as AuthenticatedAdminUtilisateursRouteImport } from './routes/_authenticated/admin/utilisateurs'
import { Route as AuthenticatedAdminVideosRouteImport } from './routes/_authenticated/admin/videos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBibliothequeRoute =
  AuthenticatedBibliothequeRouteImport.update({
    id: '/bibliotheque',
    path: '/bibliotheque',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComparaisonRoute =
  AuthenticatedComparaisonRouteImport.update({
    id: '/comparaison',
    path: '/comparaison',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMontageRoute = AuthenticatedMontageRouteImport.update({
  id: '/montage',
  path: '/montage',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatistiquesRoute =
  AuthenticatedStatistiquesRouteImport.update({
    id: '/statistiques',
    path: '/statistiques',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStoryboardRoute = AuthenticatedStoryboardRouteImport.update({
  id: '/storyboard',
  path: '/storyboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const FTokenRoute = FTokenRouteImport.update({
  id: '/f/$token',
  path: '/f/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAnalysesRoute =
  AuthenticatedAdminAnalysesRouteImport.update({
    id: '/analyses',
    path: '/analyses',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminClesApiRoute =
  AuthenticatedAdminClesApiRouteImport.update({
    id: '/cles-api',
    path: '/cles-api',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCoutsRoute = AuthenticatedAdminCoutsRouteImport.update({
  id: '/couts',
  path: '/couts',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminJournalRoute =
  AuthenticatedAdminJournalRouteImport.update({
    id: '/journal',
    path: '/journal',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminParametresRoute =
  AuthenticatedAdminParametresRouteImport.update({
    id: '/parametres',
    path: '/parametres',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminScenesRoute =
  AuthenticatedAdminScenesRouteImport.update({
    id: '/scenes',
    path: '/scenes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStoryboardsRoute =
  AuthenticatedAdminStoryboardsRouteImport.update({
    id: '/storyboards',
    path: '/storyboards',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUtilisateursRoute =
  AuthenticatedAdminUtilisateursRouteImport.update({
    id: '/utilisateurs',
    path: '/utilisateurs',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminVideosRoute =
  AuthenticatedAdminVideosRouteImport.update({
    id: '/videos',
    path: '/videos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/bibliotheque': typeof AuthenticatedBibliothequeRoute
  '/comparaison': typeof AuthenticatedComparaisonRoute
  '/montage': typeof AuthenticatedMontageRoute
  '/statistiques': typeof AuthenticatedStatistiquesRoute
  '/storyboard': typeof AuthenticatedStoryboardRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/f/$token': typeof FTokenRoute
  '/admin/analyses': typeof AuthenticatedAdminAnalysesRoute
  '/admin/cles-api': typeof AuthenticatedAdminClesApiRoute
  '/admin/couts': typeof AuthenticatedAdminCoutsRoute
  '/admin/journal': typeof AuthenticatedAdminJournalRoute
  '/admin/parametres': typeof AuthenticatedAdminParametresRoute
  '/admin/scenes': typeof AuthenticatedAdminScenesRoute
  '/admin/storyboards': typeof AuthenticatedAdminStoryboardsRoute
  '/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/admin/videos': typeof AuthenticatedAdminVideosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bibliotheque': typeof AuthenticatedBibliothequeRoute
  '/comparaison': typeof AuthenticatedComparaisonRoute
  '/montage': typeof AuthenticatedMontageRoute
  '/statistiques': typeof AuthenticatedStatistiquesRoute
  '/storyboard': typeof AuthenticatedStoryboardRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/f/$token': typeof FTokenRoute
  '/admin/analyses': typeof AuthenticatedAdminAnalysesRoute
  '/admin/cles-api': typeof AuthenticatedAdminClesApiRoute
  '/admin/couts': typeof AuthenticatedAdminCoutsRoute
  '/admin/journal': typeof AuthenticatedAdminJournalRoute
  '/admin/parametres': typeof AuthenticatedAdminParametresRoute
  '/admin/scenes': typeof AuthenticatedAdminScenesRoute
  '/admin/storyboards': typeof AuthenticatedAdminStoryboardsRoute
  '/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/admin/videos': typeof AuthenticatedAdminVideosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/bibliotheque': typeof AuthenticatedBibliothequeRoute
  '/_authenticated/comparaison': typeof AuthenticatedComparaisonRoute
  '/_authenticated/montage': typeof AuthenticatedMontageRoute
  '/_authenticated/statistiques': typeof AuthenticatedStatistiquesRoute
  '/_authenticated/storyboard': typeof AuthenticatedStoryboardRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRoute
  '/f/$token': typeof FTokenRoute
  '/_authenticated/admin/analyses': typeof AuthenticatedAdminAnalysesRoute
  '/_authenticated/admin/cles-api': typeof AuthenticatedAdminClesApiRoute
  '/_authenticated/admin/couts': typeof AuthenticatedAdminCoutsRoute
  '/_authenticated/admin/journal': typeof AuthenticatedAdminJournalRoute
  '/_authenticated/admin/parametres': typeof AuthenticatedAdminParametresRoute
  '/_authenticated/admin/scenes': typeof AuthenticatedAdminScenesRoute
  '/_authenticated/admin/storyboards': typeof AuthenticatedAdminStoryboardsRoute
  '/_authenticated/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/_authenticated/admin/videos': typeof AuthenticatedAdminVideosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/bibliotheque'
    | '/comparaison'
    | '/montage'
    | '/statistiques'
    | '/storyboard'
    | '/studio'
    | '/f/$token'
    | '/admin/analyses'
    | '/admin/cles-api'
    | '/admin/couts'
    | '/admin/journal'
    | '/admin/parametres'
    | '/admin/scenes'
    | '/admin/storyboards'
    | '/admin/utilisateurs'
    | '/admin/videos'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bibliotheque'
    | '/comparaison'
    | '/montage'
    | '/statistiques'
    | '/storyboard'
    | '/studio'
    | '/f/$token'
    | '/admin/analyses'
    | '/admin/cles-api'
    | '/admin/couts'
    | '/admin/journal'
    | '/admin/parametres'
    | '/admin/scenes'
    | '/admin/storyboards'
    | '/admin/utilisateurs'
    | '/admin/videos'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/bibliotheque'
    | '/_authenticated/comparaison'
    | '/_authenticated/montage'
    | '/_authenticated/statistiques'
    | '/_authenticated/storyboard'
    | '/_authenticated/studio'
    | '/f/$token'
    | '/_authenticated/admin/analyses'
    | '/_authenticated/admin/cles-api'
    | '/_authenticated/admin/couts'
    | '/_authenticated/admin/journal'
    | '/_authenticated/admin/parametres'
    | '/_authenticated/admin/scenes'
    | '/_authenticated/admin/storyboards'
    | '/_authenticated/admin/utilisateurs'
    | '/_authenticated/admin/videos'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FTokenRoute: typeof FTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bibliotheque': {
      id: '/_authenticated/bibliotheque'
      path: '/bibliotheque'
      fullPath: '/bibliotheque'
      preLoaderRoute: typeof AuthenticatedBibliothequeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comparaison': {
      id: '/_authenticated/comparaison'
      path: '/comparaison'
      fullPath: '/comparaison'
      preLoaderRoute: typeof AuthenticatedComparaisonRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/montage': {
      id: '/_authenticated/montage'
      path: '/montage'
      fullPath: '/montage'
      preLoaderRoute: typeof AuthenticatedMontageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statistiques': {
      id: '/_authenticated/statistiques'
      path: '/statistiques'
      fullPath: '/statistiques'
      preLoaderRoute: typeof AuthenticatedStatistiquesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/storyboard': {
      id: '/_authenticated/storyboard'
      path: '/storyboard'
      fullPath: '/storyboard'
      preLoaderRoute: typeof AuthenticatedStoryboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/f/$token': {
      id: '/f/$token'
      path: '/f/$token'
      fullPath: '/f/$token'
      preLoaderRoute: typeof FTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/analyses': {
      id: '/_authenticated/admin/analyses'
      path: '/analyses'
      fullPath: '/admin/analyses'
      preLoaderRoute: typeof AuthenticatedAdminAnalysesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cles-api': {
      id: '/_authenticated/admin/cles-api'
      path: '/cles-api'
      fullPath: '/admin/cles-api'
      preLoaderRoute: typeof AuthenticatedAdminClesApiRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/couts': {
      id: '/_authenticated/admin/couts'
      path: '/couts'
      fullPath: '/admin/couts'
      preLoaderRoute: typeof AuthenticatedAdminCoutsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/journal': {
      id: '/_authenticated/admin/journal'
      path: '/journal'
      fullPath: '/admin/journal'
      preLoaderRoute: typeof AuthenticatedAdminJournalRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/parametres': {
      id: '/_authenticated/admin/parametres'
      path: '/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AuthenticatedAdminParametresRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/scenes': {
      id: '/_authenticated/admin/scenes'
      path: '/scenes'
      fullPath: '/admin/scenes'
      preLoaderRoute: typeof AuthenticatedAdminScenesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/storyboards': {
      id: '/_authenticated/admin/storyboards'
      path: '/storyboards'
      fullPath: '/admin/storyboards'
      preLoaderRoute: typeof AuthenticatedAdminStoryboardsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/utilisateurs': {
      id: '/_authenticated/admin/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/admin/utilisateurs'
      preLoaderRoute: typeof AuthenticatedAdminUtilisateursRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/videos': {
      id: '/_authenticated/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AuthenticatedAdminVideosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAnalysesRoute: typeof AuthenticatedAdminAnalysesRoute
  AuthenticatedAdminClesApiRoute: typeof AuthenticatedAdminClesApiRoute
  AuthenticatedAdminCoutsRoute: typeof AuthenticatedAdminCoutsRoute
  AuthenticatedAdminJournalRoute: typeof AuthenticatedAdminJournalRoute
  AuthenticatedAdminParametresRoute: typeof AuthenticatedAdminParametresRoute
  AuthenticatedAdminScenesRoute: typeof AuthenticatedAdminScenesRoute
  AuthenticatedAdminStoryboardsRoute: typeof AuthenticatedAdminStoryboardsRoute
  AuthenticatedAdminUtilisateursRoute: typeof AuthenticatedAdminUtilisateursRoute
  AuthenticatedAdminVideosRoute: typeof AuthenticatedAdminVideosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAnalysesRoute: AuthenticatedAdminAnalysesRoute,
    AuthenticatedAdminClesApiRoute: AuthenticatedAdminClesApiRoute,
    AuthenticatedAdminCoutsRoute: AuthenticatedAdminCoutsRoute,
    AuthenticatedAdminJournalRoute: AuthenticatedAdminJournalRoute,
    AuthenticatedAdminParametresRoute: AuthenticatedAdminParametresRoute,
    AuthenticatedAdminScenesRoute: AuthenticatedAdminScenesRoute,
    AuthenticatedAdminStoryboardsRoute: AuthenticatedAdminStoryboardsRoute,
    AuthenticatedAdminUtilisateursRoute: AuthenticatedAdminUtilisateursRoute,
    AuthenticatedAdminVideosRoute: AuthenticatedAdminVideosRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedBibliothequeRoute: typeof AuthenticatedBibliothequeRoute
  AuthenticatedComparaisonRoute: typeof AuthenticatedComparaisonRoute
  AuthenticatedMontageRoute: typeof AuthenticatedMontageRoute
  AuthenticatedStatistiquesRoute: typeof AuthenticatedStatistiquesRoute
  AuthenticatedStoryboardRoute: typeof AuthenticatedStoryboardRoute
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedBibliothequeRoute: AuthenticatedBibliothequeRoute,
  AuthenticatedComparaisonRoute: AuthenticatedComparaisonRoute,
  AuthenticatedMontageRoute: AuthenticatedMontageRoute,
  AuthenticatedStatistiquesRoute: AuthenticatedStatistiquesRoute,
  AuthenticatedStoryboardRoute: AuthenticatedStoryboardRoute,
  AuthenticatedStudioRoute: AuthenticatedStudioRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FTokenRoute: FTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
